# KNN exercise 1

By: Ariel Bar-itzhack

In [ ]:
import pandas as ?
import numpy as ?
from sklearn.neighbors import ? #KNN classifier
from sklearn.metrics import ?_? #Accuracy Score

In [ ]:
#load dataset
df = ?.?_?('https://raw.githubusercontent.com/arielb30/datasets/main/Iris.csv')
? #show dataframe

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
#drop ID column
df.?(?,axis=?,inplace=?)
#shuffle rows
df = df.?(frac = ?)
#reset index
df.?_?(drop=?,inplace=?)
? #show dataframe

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
0              6.3           2.3            4.4           1.3  Iris-versicolor
1              4.7           3.2            1.6           0.2      Iris-setosa
2              5.1           3.7            1.5           0.4      Iris-setosa
3              6.2           3.4            5.4           2.3   Iris-virginica
4              5.8           2.6            4.0           1.2  Iris-versicolor
..             ...           ...            ...           ...              ...
145            5.0           2.3            3.3           1.0  Iris-versicolor
146            7.2           3.2            6.0           1.8   Iris-virginica
147            4.6           3.6            1.0           0.2      Iris-setosa
148            5.5           2.3            4.0           1.3  Iris-versicolor
149            6.9           3.1            5.1           2.3   Iris-virginica

[150 rows x 5 columns]

In [ ]:
#Chose attributes, all but target
X=?.?(?,axis=?).?_?()
?.? #show shape

(150, 4)

In [ ]:
#chose target
y = ?.?_?()
?.? #show shape

(150,)

In [ ]:
# create KNN classifier with K=3
knn1 = ?(n_neighbors = ?)
# fit to data
?.?(?,?)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
#predict on 3 samples (make up numbers for features)
?.?(?)

array(['Iris-setosa', 'Iris-virginica', 'Iris-versicolor'], dtype=object)

In [ ]:
#predict on all samples
y_pred = ?.?(?)
?.? #show shape

(150,)

In [ ]:
#show only 5 predictions
?_?[?]

array(['Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor'], dtype=object)

In [ ]:
#accuracy using classifier,X,y
?.?(X=?,y=?)

0.96

In [ ]:
#accuracy using y and y_pred
?_?(y_true=?, y_pred = ?_?)

0.96