### By Ariel Bar-itzhack

In [ ]:
import pandas as pd
import numpy as np
#from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [ ]:
#load dataset
df = pd.read_csv('https://raw.githubusercontent.com/arielb30/datasets/main/Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
#drop ID column
df.drop(?,axis=?,inplace=?)
#shuffle rows
df = df.?(frac = ?,random_state=1)
#reset index
df.reset_index(drop=?,inplace=?)
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
0              5.8           4.0            1.2           0.2      Iris-setosa
1              5.1           2.5            3.0           1.1  Iris-versicolor
2              6.6           3.0            4.4           1.4  Iris-versicolor
3              5.4           3.9            1.3           0.4      Iris-setosa
4              7.9           3.8            6.4           2.0   Iris-virginica
..             ...           ...            ...           ...              ...
145            6.3           2.8            5.1           1.5   Iris-virginica
146            6.4           3.1            5.5           1.8   Iris-virginica
147            6.3           2.5            4.9           1.5  Iris-versicolor
148            6.7           3.1            5.6           2.4   Iris-virginica
149            4.9           3.1            1.5           0.1      Iris-setosa

[150 rows x 5 columns]

### K Nearest neighbour function

In [ ]:
def KNN_predict_sample(df, sample, k):
  dfnp = ?.drop(?,axis=?).to_?() #drop species column and convert to numpy
  dis2 = np.linalg.?(? - ?,axis=?) #linear algebra norm
  df2 = ?.?() #copy dataframe
  ?[?] = pd.Series(?) #add distance column
  ?.sort_?(by=?,ascending=?,inplace=?) #sort by distance
  top_k = ?[?].iloc[:?] #top k rows of Species column
  return top_k.?_?().?() #compute value counts and idxmax

In [ ]:
def KNN_predict(df,samples,k):
    preds = [?_?_?(?,?,?) for ? in ?] #list comprehension on predictions
    return np.?(?,dtype=object) #return numpy array

In [ ]:
k=5
sample = np.array([[0,1,2,3]])
sample

array([[0, 1, 2, 3]])

In [ ]:
samples = np.array([[1,1,1,1],[4,4,4,4],[5,2,3,1]])
samples

array([[1, 1, 1, 1],
       [4, 4, 4, 4],
       [5, 2, 3, 1]])

In [ ]:
#predict on 1 sample
KNN_predict(?,?,?)

array(['Iris-setosa'], dtype=object)

In [ ]:
#predict on 3 samples
KNN_predict(?,?,?)

array(['Iris-setosa', 'Iris-virginica', 'Iris-versicolor'], dtype=object)

In [ ]:
#Chose attributes
X=?.drop(?,axis=?).to_?() #all but target
X.shape

(150, 4)

In [ ]:
#chose target
y = ?[?].to_?()
y.shape

(150,)

In [ ]:
#predict on all samples
y_pred= ?_?(?,?,?)
?[:10]

array(['Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica'], dtype=object)

In [ ]:
#show real labels
?[:10]

array(['Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica'], dtype=object)

In [ ]:
#accuracy using y and y_pred
accuracy_score(y_true=?, y_pred = ?)

0.9666666666666667